name: Release PDF on Publish

on:
  release:
    types: [published]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Typst
      - uses: typst-community/setup-typst@v3

      # Compile the Typst file to PDF
      - name: Compile Typst file
        run: typst compile --font-path fonts main.typ bupt-network-resources-guide.pdf

      # Upload the PDF to the release
      - name: Upload PDF to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bupt-network-resources-guide.pdf
          asset_name: bupt-network-resources-guide.pdf
          asset_content_type: application/pdf
